### ISSUE TITLE
request for abort action using URI call

### ISSUE THREAD

**Issue by teicher** [sumup/sumup-android-api#1]
Hello, apologies if you do not want issues created here, you did not give any discussion forum or other bug tracker...

My major fear with using "URI call" option is that payment will performed in SumUp after checkout has been cancelled / timeouted etc in the calling app, thus the success call will not or too late reach my calling App.
(Thus customer might have added or removed items from the bill in the meanwhile, changing the total amount....)

Would it be possible to itroduce an "abort" URI call ? e.g.

```
new Intent(Intent.ACTION_VIEW, Uri.parse("sumupmerchant://cancelpayment/1.0"
                                + "?affiliate-key="YOUR_AFFILIATE_KEY""
                                + "&foreign-tx-id=" + mytxid

```

Cheers, Tom.

**Comment by ultrah** [comment]
Hi Tom,

this is the right place to create issues, no worries. 

How would a user alter the payment while the Sum Up payment is in progress? The Sum Up app is in foreground at that point, so we don’t see how the user can alter it on the device.

In any case, we are currently not planning to add this kind of callback. You would need to make sure that the payment can not be altered on your end while the Sum Up payment is in progress.

Best,

Philipp

**Comment by teicher** [comment]
Hello,

well in a classic counter setup, the POS is facing the cashier and the Customer-Display is facing the customer, so we are planning to execute the payment on the Customer-Display, no the POS.

In any case, Apps can hang and crash, the pin+ can hang or it's battery die, the network can lag or break down ... and we can't render the POS unusable (even for cash transaction) just because a SumUp payment is "in limbo"...
I guess it's impossible to really "make sure that the payment can not be altered on your end while the SumUp payment is in progress"...

I guess the safest way is to not wait for activity result (potentially forever) but to maybe poll the
`https://api.sumup.com/v0.1/me/transactions?foreign_transaction_id=XXX` every X seconds until payment settled or failed ... what do you think as a solution for this ?

Thanks, Tom.

**Comment by ultrah** [comment]
Hi Tom, the cases you describe are why we added the foreign-transaction ID field. I would recommend you wait for the activity result and when you think something went wrong on the SumUp side, start polling the API. Otherwise you might run into rate-limiting on our backend at some point.
