### ISSUE TITLE
How does this plugin differ from sumup-android-sdk?

### ISSUE THREAD

**Issue by larssn** [sumup/sumup-android-api#10]
Topic

**Comment by JullianSU** [comment]
Hi, 

Please find the documentation regarding our SDK and APIs [here](http://docs.sumup.com/terminal-payment/#terminal-payment-sdk)

Do not hesitate to get back to us if you have any further questions.

**Comment by larssn** [comment]
Well the topic question was my main question. But it's fine, I no longer require that information, as we're not using this.
