### ISSUE TITLE
👨‍💻Running app into Raspberry Pi

### ISSUE THREAD

**Issue by maguri** [sumup/sumup-android-api#18]
Hello Sumup team,

I sent you an email, but I think we can start the contact from here.

I'm building a Payment program which will run into a **Raspberry Pi** and I would like to integrate the Sumup Terminal I received.

This program is part as an Automated system without Human interaction from our side:

```
External Device Inputs-->[Machine<-->Sumup Terminal]<--> Customer
```
Is there any way to communicate my ruby app with the physical terminal programming hardly with the Bluetooth implementation **without using your Android SDK**? I cannot run Android for this project.

I was thinking using **Bluetooth Connection** + **Sumup Web-API** to proceed with the payment auth.

The only think is missing is the communications Protocol your android app uses to communicate with the corresponding Terminal: `Pairing, I/O Data, ...`

I could build an open source library for you with your support 😁

**Comment by maguri** [comment]
I will run Android into a Raspberry and use your Android SDK to connect with the TPV.

- https://source.android.com/
- https://developer.android.com/things

**Comment by tinolan** [comment]
Hey,

Did you solve your problem?
I have the same idea to run Android things on a Raspberry 3, but can't connect to the SumUp Terminal or start a payment.

Can you help me?
Is your code on github?

Greetings Tino!

**Comment by maguri** [comment]
hi Tino,

Sorry but we didn't keep walking through this path...

We needed a very robust and unattended solution for payments and we finally decided to do it with an embedded payment terminal dedicated 100% to do that.

By the way, there is a way you can install android OS into your raspberry pi and use your App there, but still not being the best solution if you will let any user to interact with your Raspberry.

Best Regards,

**Comment by tinolan** [comment]
Hi @maguri,

Thanks for your answer!
Too bad you changed your system.

I can't run normal android OS into my raspberry, because i need the GPIO's to communicate with another system.
That's why i need Android Things, but I can't get it to run.

Best regards!

**Comment by arnolde** [comment]
@maguri Would you mind mentioning which embedded payment terminal you use? I'm also considering Sumup since it's the only one I know of without monthly fees, and really cheap hardware.

**Comment by maguri** [comment]
@arnolde - We now use and supply this: Spu90R + Spu90C
[Spu90R.pdf](https://github.com/sumup/sumup-android-api/files/7555033/Spu90R.pdf)
[Spu90C.pdf](https://github.com/sumup/sumup-android-api/files/7555052/Spu90C.pdf)
**Only contactless payments**

Let me know if you need a quotation.
