### ISSUE TITLE
timeouted payment can never be completed

### ISSUE THREAD

**Issue by teicher** [sumup/sumup-android-api#2]
When calling up a payment like
`sumupmerchant://pay/1.0?affiliate-key=XXXXX&app-id=XXXXX&amount=1.00&currency=EUR&title=ICard-Payment&receipt-mobilephone=+491720000&receipt-email=xxx@xxx.de&foreign-tx-id=2-1001-54-20160415-7&callback=mycallbackscheme://result`
then letting the "insert card" time out, any further attempt to start payment for the same `foreign-tx-id` will just fail "Die Zahlung konnte aufgrund von Netzwerkproblemen nicht durchgeführt werden. Die Karte wurde nicht belastet. Sie können die Durchführung der Zahlung noch einmal versuchen."
Contrary to what is written, it probably not a network issue, and no retry will ever succeed.

```
E/SumUp   ( 4282): (SourceFile:31)@main | Event rpcEventCheckout - Reason:
E/SumUp   ( 4282): (SourceFile:31)@main | Error for in emv response:
...
java.io.FileNotFoundException: https://static.sumup.com/images/checkout/result/connection_error@1.5x.png?v=5
```

It works well again for any other `foreign-tx-id`

**Comment by ultrah** [comment]
We are aware of this issue, it will be fixed in a future version of the app

**Comment by ultrah** [comment]
Thank you for reporting anyway!

**Comment by teicher** [comment]
Does this effect only special cases or all usages of `foreign-tx-id`?
Are there any known workarounds ? (This renders all safeguards discussed in issue 1 unusable... )

Any timeline for the fix? (days, months, far future)
(We are currently unsure whether we should continue with sumup integration at all at this point...)

**Comment by ultrah** [comment]
Not sure how this relates to issue 1, can you elaborate? As documented, foreign-tx-id` has to be unique in the scope of the merchant account, so the behaviour of the app is as expected - Just the error you get back is wrong.

If your issue is with the misleading error message, we can put the fix for this into the development pipeline. We are currently in release preparation for the next app release, so the fix for this bug will not make it into the next version. The one after that should be feasible though. If this is too long for you, we can supply you a test version for development.

**Comment by teicher** [comment]
No, I do not care for a wrong error message.
My problem is:
* payment is attempted for foreign-tx-id 123
* and fails for whatever reason
* now 123 is still unpaid in pos
* thus another payment is attempted foreign-tx-id 123
* but will never succeed.
* To successfully pay the bill with sumup, we must total-void in the pos, and reenter all positions so it will become new tx 124 ...

**Comment by ultrah** [comment]
This behaviour is as expected. We have to keep a record for each transaction attempt, it it is successful or not. If you start a transaction with foreign-tx-id 123, you need to use a different one for the second attempt. Otherwise foreign-tx-id could not uniquely identify a transaction.

**Comment by teicher** [comment]
Okay, so `foreign-tx-id` is not meant to be the POS-side's own transaction id, but just a POS-generated unique-id-per-payment-attempt.
So this must be remembered (persistently) on the POS side for each POS transaction if we want to be able to use `https://api.sumup.com/v0.1/me/transactions?foreign_transaction_id=XXX` in order to query if a broken/crashed/timeouted (on POS side) payment attempt was successful in SumUp app anyway...
Okay, this is doable, albeit with unexpected additional work on POS side...

**Comment by ultrah** [comment]
Yes, exactly. We will discuss if we can make the documentation more clear at this point.
