### ISSUE TITLE
Bluetooth access - where is the Java code or library?

### ISSUE THREAD

**Issue by martijintro** [sumup/sumup-android-api#20]
Hi there!

How is that handled? Can't see any bluetooth-access related Java code.

Thank you very much for your feedbacks.

With best regards,
Jan

**Comment by JullianSU** [comment]
Hi Jan, 

Thank you for your email, we are taking care of this part of the code and make sure our integrated product is working with the biggest range of mobile devices. 

What are your needs to access this code? 

Many thanks,

**Comment by martijintro** [comment]
I would like to control the bluetooth terminal with a system that uses platform-independent, standard Java code. (Maybe with OS-specific services and libraries)

Is that possible, is the bluetooth transfer method between the Sumup Android app and the SumUp Bluetooth Terminal open or closed?

**Comment by martijintro** [comment]
generally possible or not?

**Comment by martijintro** [comment]
Question is still pendent...

**Comment by martijintro** [comment]
No anwser may be an anwser too...?!?

"Yes" or "No" is enough...

Thx!!!

**Comment by martijintro** [comment]
"Is that possible, is the bluetooth transfer method between the Sumup Android app and the SumUp Bluetooth Terminal open or closed?"

-> NO ANSWER?!?

**Comment by martijintro** [comment]
LOL... problem solved by using another solution!!
