### ISSUE TITLE
How to identify a completed transaction with the given Intent

### ISSUE THREAD

**Issue by rivella50** [sumup/sumup-android-api#4]
Hi,
in our app a user chooses from a list of open transactions (each one defined with a unique foreignTransactionId) which one to use next for payment.
Is there a way we can retrieve such a completed transaction in onActivityResult(..) with the
data given back in the Intent parameter?
In our opinion SumUpAPI.Response doesn't contain any information which we could use to match with the transactions from the original list.
SumUpAPI.Response.TX_CODE is not the same as the foreignTransactionId, right?

If there is no identifying feature we would have set the current transaction in a separate field in our app, but we think it would be neater to use the data in the Intent.

**Comment by rivella50** [comment]
Problem solved:

```
Bundle extra = data.getExtras();
String foreignTransactionId = extra.getString(SumUpAPI.Param.FOREIGN_TRANSACTION_ID);
```

**Comment by vfoixcable** [comment]
You were quicker than. I was about to send you the same. We forgot to document that point and will fix that in a very near future.

**Comment by rivella50** [comment]
That's great. Thank you for your message.
