### ISSUE TITLE
Login doesn't work

### ISSUE THREAD

**Issue by Gigibit** [sumup/sumup-android-api#9]
I've tried to login with the same credentials in the dashboard but it does not send me across.
Already configured affialted key, but no change.
The error is:
Event rpcEventLogin - Reason: These login details are not valid. Please check your username and password and try again.

**Comment by vfoixcable** [comment]
It sounds like you created an api key with an application identifier which does not match the identifier of the app you want to use with SumUp with.

If you still cannot manage to make it work, please reach out to integration@sumup.com!
